### ISSUE TITLE
vagrant up is failed

### ISSUE THREAD

**Issue by nyasukun** [dmorrill10/acpc_vagrant#1]
I got following error:

> Chef never successfully completed! Any errors should be visible in the
> output above. Please fix your recipes so that they properly complete.

full message of vagrant up is pasted at this gist:
https://gist.github.com/nyasukun/e9b58afcdf6eb6060b508d36a8335839

**Comment by dmorrill10** [comment]
Hmm, it looks like cookbooks aren't installed. Did you run `librarian-chef install` (step 4 in the installation instructions)?

**Comment by nyasukun** [comment]
Sorry I misunderstood instruction.
So this issue is invalid.
